// SPDX-License-Identifier: BSL-1.1
// GENERATED by packages/circuits/scripts/build.sh — do not edit by hand.
pragma solidity ^0.8.24;

import "./IGroth16Verifier.sol";
import "./Groth16VerifierCore.sol";

/// @title Groth16VerifierProduction
/// @notice Production Groth16 verifier for the BeneficiaryEntitlement circuit.
///         Wraps the snarkjs-generated BN254 pairing verifier (Groth16VerifierCore)
///         and implements IGroth16Verifier for use by TransferVaultFactory.
///         IS_PRODUCTION_VERIFIER = true.
///
///         All four public inputs are cryptographically enforced simultaneously by
///         the BN254 pairing check:
///           [0] merkleRoot         — vault.beneficiaryRoot
///           [1] nullifierHash      — Poseidon(secret, vaultAddress)
///           [2] vaultAddress       — uint160(vault address)
///           [3] beneficiaryDestHash — Poseidon(secret, destinationSalt)
contract Groth16VerifierProduction is IGroth16Verifier {
    /// @notice Runtime guard: always true for this production verifier.
    bool public constant IS_PRODUCTION_VERIFIER = true;

    /// @notice Verifier grade stamp. Mirrors the STAGING/PRODUCTION
    ///         split enforced by deployment tooling.
    bytes32 public constant VERIFIER_GRADE = keccak256("PRODUCTION");

    Groth16VerifierCore private immutable _core;

    constructor() {
        _core = new Groth16VerifierCore();
    }

    /// @inheritdoc IGroth16Verifier
    function verifyProof(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[4] calldata publicInputs
    ) external view returns (bool) {
        return _core.verifyProof(a, b, c, publicInputs);
    }
}
